security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    role_hierarchy:
        ROLE_USER:      IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN:     ROLE_MODERATOR

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }