parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    register_service:
        class: AppBundle\Service\RegisterService
        public: true
        arguments:
            - '@doctrine'

    forgot_password:
        class: AppBundle\Service\ForgotService
        public: true
        arguments:
            - '@doctrine'
            - '@mailer'

    reset_password:
        class: AppBundle\Service\ResetService
        public: true
        arguments:
            - '@doctrine'
