parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    login_service:
        class: AppBundle\Service\LoginService
        public: true
        arguments:
            - '@doctrine'

    register_service:
        class: AppBundle\Service\RegisterService
        public: true
        arguments:
            - '@doctrine'

    forgot_password:
        class: AppBundle\Service\ForgotService
        public: true
        arguments:
            - '@doctrine'
            - '@mailer'

    reset_password:
        class: AppBundle\Service\ResetService
        public: true
        arguments:
            - '@doctrine'

    category:
        class: AppBundle\Service\CategoryService
        public: true
        arguments:
            - '@doctrine'

    products:
        class: AppBundle\Service\ProductService
        public: true
        arguments:
            - '@doctrine'

    serialize_service:
        class: AppBundle\Service\SerializeService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }
            - { name: knp_menu.menu_builder, method: createSmallMenu, alias: accordeon }
